apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mohammadrezachegini/fullstack-gitops-argocd
    targetRevision: master
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true